### ISSUE TITLE
Index error when calculating qubit count for `QROAMClean().adjoint()`

### ISSUE THREAD

**Issue by alxvov** [quantumlib/Qualtran#1548]
Here is the script:

```python3
import numpy as np
from qualtran.bloqs.data_loading.qroam_clean import (
    QROAMClean,
)
from qualtran.resource_counting import get_cost_value, QubitCount

data1 = np.tile(np.arange(256), (14, 1))
data2 = np.tile(np.arange(256), (14, 1))
t1bits = 8
t2bits = 32
log_block_size = (0, 1)

qroam = QROAMClean.build_from_data(
    data1,
    data2,
    target_bitsizes=(t1bits, t2bits),
    log_block_sizes=log_block_size,
)


qubit_count = get_cost_value(
    qroam.adjoint(),
    QubitCount(),
)
print(qubit_count)
```

and the error is

```bash
Traceback (most recent call last):
  File "/Users/aleksei/Software/quantum_resource_estimates/Qualtran/qualtran/resource_counting/_qubit_counts.py", line 111, in compute
    cbloq = bloq.decompose_bloq()
  File "/Users/aleksei/Software/quantum_resource_estimates/Qualtran/qualtran/_infra/bloq.py", line 144, in decompose_bloq
    return _decompose_from_build_composite_bloq(self)
  File "/Users/aleksei/Software/quantum_resource_estimates/Qualtran/qualtran/_infra/bloq.py", line 56, in _decompose_from_build_composite_bloq
    out_soqs = bloq.build_composite_bloq(bb=bb, **initial_soqs)
  File "/Users/aleksei/Software/quantum_resource_estimates/Qualtran/qualtran/bloqs/data_loading/qroam_clean.py", line 258, in build_composite_bloq
    self.qroam_clean.target_registers, self.qroam_clean_adjoint_bloq.target_registers
  File "<attrs generated getattr qualtran.bloqs.data_loading.qroam_clean.QROAMCleanAdjointWrapper>", line 6, in __getattr__
    result = func(self)
  File "/Users/aleksei/Software/quantum_resource_estimates/Qualtran/qualtran/bloqs/data_loading/qroam_clean.py", line 238, in qroam_clean_adjoint_bloq
    *self.qroam_clean.batched_data_permuted,
  File "<attrs generated getattr qualtran.bloqs.data_loading.qroam_clean.QROAMClean>", line 6, in __getattr__
    result = func(self)
  File "/Users/aleksei/Software/quantum_resource_estimates/Qualtran/qualtran/bloqs/data_loading/qroam_clean.py", line 422, in batched_data_permuted
    curr_data = swz.call_classically(**sel_kwargs, targets=np.copy(data[sel_l]))[-1]
  File "/Users/aleksei/Software/quantum_resource_estimates/Qualtran/qualtran/_infra/bloq.py", line 227, in call_classically
    res = self.as_composite_bloq().on_classical_vals(**vals)
  File "/Users/aleksei/Software/quantum_resource_estimates/Qualtran/qualtran/_infra/composite_bloq.py", line 220, in on_classical_vals
    out_vals, _ = call_cbloq_classically(self.signature, vals, self._binst_graph)
  File "/Users/aleksei/Software/quantum_resource_estimates/Qualtran/qualtran/simulation/classical_sim.py", line 213, in call_cbloq_classically
    _binst_on_classical_vals(binst, pred_cxns, soq_assign)
  File "/Users/aleksei/Software/quantum_resource_estimates/Qualtran/qualtran/simulation/classical_sim.py", line 177, in _binst_on_classical_vals
    out_vals = bloq.on_classical_vals(**in_vals)
  File "/Users/aleksei/Software/quantum_resource_estimates/Qualtran/qualtran/bloqs/swap_network/swap_with_zero.py", line 209, in on_classical_vals
    if selection_idx[i] & (1 << sel_idx_small) != 0:
IndexError: tuple index out of range
```

This problem does not occur when using qroam without adjoint. Might be related to #1541

**Comment by mpharrigan** [comment]
I think this is actually related to #1547 -- there seem to be bugs around a `log_block_size=0`.  Note that you can trigger the error by just trying to decompose  `qroam.adjoint().decompose_bloq()` and a different (but presumably related error) with `qroam.decompose()`

using `log_block_size=(1,1)` allows these calls and qubit count to complete. I'm trying to figure out what we should do with 0's in log_block_sizes

**Comment by mpharrigan** [comment]
This should be fixed by #1578 !

**Comment by alxvov** [comment]
Hi @mpharrigan, 

I just tried to run this example with the latest main and I still get the same error. Can you reproduce the bug?

Best wishes,
Aleksei

**Comment by mpharrigan** [comment]
You're right. The `log_block_size` of zero appears to be causing another issue in `SelectSwapQROM`'s `SwapWtihZero` subbloqs (via the `swap_with_zero_bloqs` property. The `log_block_sizes` gets passed to `SwapWithZero`'s `selection_bitsizes`, and I assume it doesn't like having a zero-bitsize register

investigation will continue

**Comment by mpharrigan** [comment]
`SwapWithZero` will filter out bitsize-zero entries, so only one selection register remains; but `on_classical_vals` is indexing into a list of its inputs where it expects at least two selection registers

**Comment by mpharrigan** [comment]
<img width="1073" alt="Image" src="https://github.com/user-attachments/assets/4f9d6b4a-ca99-4a74-a7be-d6a6fb2a1ae6" />

This `zip` is dropping entries from `sel_k` because `swz.selection_registers` filters out the zero-bitsize things
